# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ADService
DESTDIR = ../x64/Debug
CONFIG += debug console
LIBS += -L"." \
    -l/"$(INHERIT)/" \
    -l$(Qt_LIBS_) \
    -lWtsapi32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(ADService.pri)
